### ISSUE TITLE
Table of Contents sidebar in FAQs is squished 

### ISSUE THREAD

**Issue by seckroth** [HistoryAtState/hsg-shell#247]
https://history.state.gov/about/faq/where-are-state-records

![screen shot 2016-09-15 at 10 57 27 am](https://cloud.githubusercontent.com/assets/7490970/18554785/5836dbea-7b33-11e6-9ea9-9648c22954fc.png)

**Comment by joewiz** [comment]
Confirmed on iPad (iOS 10.9, Safari, landscape). @line-o Would you be able to take a look?

**Comment by joewiz** [comment]
Sorry, @line-o :), I meant @plutonik-a. I was typing on my phone and mixed your handles up. @plutonik-a Would you be able to take a look? (cc: @wolfgangmm).

**Comment by plutonik-a** [comment]
What happens is a duplication of the `<aside>` plus an extra `<div>` element, but it only appears on production site, not on the current development version!

**Development version**
<img width="388" alt="bildschirmfoto 2016-09-23 um 16 40 14" src="https://cloud.githubusercontent.com/assets/1157669/18790319/a050d742-81ae-11e6-860e-83f8d957d4de.png">

**Live version**
<img width="363" alt="bildschirmfoto 2016-09-23 um 16 40 28" src="https://cloud.githubusercontent.com/assets/1157669/18790405/f12871ac-81ae-11e6-9968-a1ad2a4909d3.png">

This bug applies to a all templates that call the function `toc:table-of-contents-sidebar`, which is a fairly great amount of pages!
[/modules/frus-toc-html.xqm#L29-L47](https://github.com/HistoryAtState/hsg-shell/blob/master/modules/frus-toc-html.xqm#L29-L47)
Nobody has touched this function since March and it definitely also worked well after that.

I thought, that maybe the function statement `%templates:wrap` interferes somehow and deleted it, but as I said, locally everything works fine.

Maybe my guess is right, or can you think of anything else, that might interfere in the live environment?

**Comment by joewiz** [comment]
I've just redeployed hsg-shell to the production servers, and it appears to have fixed the sidebar problem.  How strange - I can't explain it, except that perhaps the hsg-shell was out of date or inconsistent with the master branch in github.  (The replication system has some issues that @dizzzz is helping us work through.  Because of these issues we've been patching hsg-shell rather than redeploying it in full, which I'd prefer we do.)  Thanks for investigating this!
