### ISSUE TITLE
Prevent indentation of certain lists

### ISSUE THREAD

**Issue by joewiz** [HistoryAtState/hsg-shell#259]
As currently styled in hsg-shell, FRUS "Lists of Persons," "Lists of Terms and Abbreviations," and "Indexes" are indented. The top level content-bearing list should be flush left; only content-bearing sub-lists, such as index sub-entries, should be indented. 

This phenomenon is magnified in recent volumes, such as frus1977-80v30, in which our typesetter grouped the entries in the List of Persons by letter, giving a sub-list to each group:

> ![screen shot 2016-11-22 at 9 56 24 am](https://cloud.githubusercontent.com/assets/59118/20528371/f81678a0-b099-11e6-9148-708124cc80d8.png)

As a result, with current styling, the List is double-indented:

> ![screen shot 2016-11-22 at 9 55 30 am](https://cloud.githubusercontent.com/assets/59118/20528344/d9550e04-b099-11e6-852c-0eb109c363eb.png)

See https://history.state.gov/historicaldocuments/frus1977-80v30/persons and http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1977-80v30/persons. In print, this appears not as indentation but as a slight space between letter groups:

> ![screen shot 2016-11-22 at 9 59 12 am](https://cloud.githubusercontent.com/assets/59118/20528485/5a47864a-b09a-11e6-96f5-609ba30b7885.png)

I imagine an approach where we add some hook like a `@rendition` or `@type` attribute on the outer list that triggers a PM or CSS style that applies the desired style: no indentation for lists of persons and terms and abbreviations, but a slight space between letter groups. But I'm open to your suggestions.

**Comment by tuurma** [comment]
div[@xml:id='persons'] (or 'terms' and so on) should have unindented top-level lists
similar treatment might be beneficial also in index pages

**Comment by tuurma** [comment]
@plutonik-a there is now a special case model for the lists in question, it doesn't affect the display yet though, I've just given them a list-person css class for the time being. I'd like your help here:

- to supply the css that prevents the superfluous indentation
- please comment if naming of css class sits well with the scheme you have developed

**Comment by plutonik-a** [comment]
1. All lists with class `tei-list5` get this superfluous indentation `padding-left: xy;` as a default style by the browser, because it is not reset to 0 in the `ODD`.    
Seen in i.e. [local: sources](http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1977-80v30/sources) and [online: sources](https://history.state.gov/historicaldocuments/frus1977-80v30/sources).  
We need to reset all  `tei-list5` lists with `padding: 0;` and then set all nested children lists to the wanted indentation value.

2. I tried to fix it in `frus.odd`, but am not sure, if this is the right element I wanted to catch, plus the wrapping `ul` needs the padding-reset. Also unsure, where the correct element is to apply the style to... Commit c67ecb9

<img width="1000" alt="bildschirmfoto 2017-03-22 um 19 51 46" src="https://cloud.githubusercontent.com/assets/1157669/24215611/971d9066-0f39-11e7-8de3-a9e00031db49.png">

3. My CSS solution is simple and fixes the layout, but should be applied to `frus.odd`. Commit 433a7f2

<img width="794" alt="bildschirmfoto 2017-03-22 um 19 33 31" src="https://cloud.githubusercontent.com/assets/1157669/24216081/32f1846a-0f3b-11e7-8368-c4334b8a7ce8.png">

<img width="688" alt="bildschirmfoto 2017-03-22 um 19 34 01" src="https://cloud.githubusercontent.com/assets/1157669/24216100/411fed2e-0f3b-11e7-9eca-f50dc43513ce.png">

**Comment by tuurma** [comment]
Thanks for today's work @plutonik-a. I have deleted the outputRendition altogether in 77920ad
 from corresponding ODD model and since we need the css to be anchored to a stable class name I've applied the CSS you came up with to list-person class. Please could you review the scss file if it needs any corrections. My display is slightly different that above (no indentation on subsequent lines of person entries)

![image](https://cloud.githubusercontent.com/assets/449468/24223389/d5764fec-0f4d-11e7-8f35-48249034702c.png)

**Comment by plutonik-a** [comment]
The PR https://github.com/HistoryAtState/hsg-shell/pull/274 is ready for review.  

While testing my changes, I fixed some `ul` list bugs that haven't been reported yet:

* http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1977-80v30/index
<img width="670" alt="bildschirmfoto 2017-03-23 um 18 42 42" src="https://cloud.githubusercontent.com/assets/1157669/24263415/5cdd34fa-0ffd-11e7-8b5d-5b7ea350270f.png">

* http://localhost:8080/exist/apps/hsg-shell/historicaldocuments/frus1977-80v30/terms
<img width="676" alt="bildschirmfoto 2017-03-23 um 18 33 26" src="https://cloud.githubusercontent.com/assets/1157669/24263540/b438eb2c-0ffd-11e7-8626-733f07ee0d8c.png">
