### ISSUE TITLE
[search] volume/administration/date filters only active when Historical Documents are

### ISSUE THREAD

**Issue by tuurma** [HistoryAtState/hsg-shell#302]

**Comment by plutonik-a** [comment]
Fixed with https://github.com/HistoryAtState/hsg-shell/commit/28c3d8b1cbca6eb4867092882909d0c20e499633, https://github.com/HistoryAtState/hsg-shell/commit/dda98e8462e5df2daeab69a7657395820aeb0ce3, https://github.com/HistoryAtState/hsg-shell/commit/fedb121a59f36b44802aed68bf66046c45234aa9.

@joewiz 
I added hint texts for the users to indicate a hidden element and how to select it.  
This is how it looks in the sidebar:
<img width="319" alt="bildschirmfoto 2017-12-01 um 14 50 39" src="https://user-images.githubusercontent.com/1157669/33485579-29ea0b92-d6a7-11e7-999f-9317775b71b3.png">

**Comment by joewiz** [comment]
@plutonik-a Looks great, thanks! Good plan.
